### PR TITLE
feat(i18n): add Occitan language

### PR DESCRIPTION
**Pull request by ensag-dev**
I hope it's correct to contribuite this way!

### CODE REVIEW

**Comment by dargmuesli** [comment]
Thank you for the PR! See https://github.com/dargmuesli/nuxt-cookie-control/discussions/83#discussioncomment-5519954 to see what's missing ;)

**Comment by ensag-dev** [comment]
> Thank you for the PR! See [#83 (comment)](https://github.com/dargmuesli/nuxt-cookie-control/discussions/83#discussioncomment-5519954) to see what's missing ;)

made the changes! I hope it will work

**Comment by dargmuesli** [comment]
I fixed a minor linting issue for you :rocket:

**Comment by ensag-dev** [comment]
thank you @dargmuesli !

**Pull request merged**
