### PR TITLE
feat: add support khmer language

### PR DESCRIPTION
**Pull request by chantouchsek**
### 📚 Description
Add locale support for Khmer Language

### 📝 Checklist

- [x] All commits follow the Conventional Commit format
- [x] The PR's title follows the Conventional Commit format

### CODE REVIEW

**Review by dargmuesli — COMMENTED** [review]
Thank you! The addition to `Locales` in `src/runtime/types.ts` is missing, see [CONTRIBUTING.md#locales](https://github.com/dargmuesli/nuxt-cookie-control/blob/master/CONTRIBUTING.md#locales) for full instructions.

**Comment by chantouchsek** [comment]
> Thank you! The addition to `Locales` in `src/runtime/types.ts` is missing, see [CONTRIBUTING.md#locales](https://github.com/dargmuesli/nuxt-cookie-control/blob/master/CONTRIBUTING.md#locales) for full instructions.

@dargmuesli Updated.

**Review by dargmuesli — APPROVED** [review]
Thank you! :green_heart:

**Pull request merged**
