### PR TITLE
feat(lang): Add Bulgarian language

### PR DESCRIPTION
**Pull request by VentsislavBorislavov**
### 📚 Description

This change adds Bulgarian localization for the cookie strings.

### 📝 Checklist

- [x] All commits follow the Conventional Commit format
- [x] The PR's title follows the Conventional Commit format

### CODE REVIEW

**Review by dargmuesli — APPROVED** [review]

**Comment by dargmuesli** [comment]
When you committed you changes, didn't the [lint commit hook](https://github.com/dargmuesli/nuxt-cookie-control/blob/09f8d0b48a12682d7bbfd0a163abafeae264cc51/.husky/pre-commit) run for you and show that indentation could be improved? I'm wondering because many PRs have complaining linting recently.

**Comment by VentsislavBorislavov** [comment]
No, the hook didn't work

**Comment by VentsislavBorislavov** [comment]
I can check the issue and update my pr

**Comment by dargmuesli** [comment]
How did you commit? Using `git add -A && git commit -m "message"` or did you use a GUI?

**Comment by VentsislavBorislavov** [comment]
I used the git extension for vs code.

**Comment by dargmuesli** [comment]
Hmm, should work in vs code too - if `pnpm i` is run first of course. Thank you for your contribution!

**Pull request merged**
