### PR TITLE
feat: add "isModalForced" to ModuleOptions

### PR DESCRIPTION
**Pull request by yoshito-maeoka**
### 📚 Description

this commit allow to force to display Cookie Modal.
that means to force users to choose any options for cookie setting.

### 📝 Checklist

- [x] All commits follow the Conventional Commit format
- [x] The PR's title follows the Conventional Commit format

### CODE REVIEW

**Review by dargmuesli — COMMENTED** [review]
Setting the new option to true, the modal is shown on every page load, which I do not expect.

**Comment by yoshito-maeoka** [comment]
thank you for your testing, and sorry, that was not also my expectation.
I fixed it.

**Comment by dargmuesli** [comment]
Thank you. Pleas ensure all commits follow the Conventional Commit format: https://www.conventionalcommits.org/en/v1.0.0/
Also, `master` needs to be merged into this branch again, I suppose, to make the build go green :green_apple:

**Comment by yoshito-maeoka** [comment]
I did not understand the Error above on ubuntu. Is there anything I can  do for that?

**Comment by dargmuesli** [comment]
There is a linter error and a warning that need to be resolved. You can see them running `pnpm lint` in your fork and even under: https://github.com/dargmuesli/nuxt-cookie-control/pull/78/files.

**Comment by dargmuesli** [comment]
Have you run `pnpm install` beforehand? This project's dependencies change regularly.

**Comment by yoshito-maeoka** [comment]
yes, but it does not help to fix...

**Comment by yoshito-maeoka** [comment]
got it.
I placed wrong directory this project, and that caused error and can not figured out until now.
but all things go fine now. 
thank you for your time to check!

**Review by dargmuesli — COMMENTED** [review]
When the user rejects all cookies, the modal is shown on the next page load. Is this intended?

**Comment by yoshito-maeoka** [comment]
actually yes. because necessary cookies should be allowed by user. 
but let me know how it should be, if you don't intend this behaviour.

**Comment by dargmuesli** [comment]
Well, if it's possible to hide the modal and use the page by pressing "decline all"... then it does not make sense to me to later show the modal again. You get the idea?

**Comment by yoshito-maeoka** [comment]
you are right. thus I hide close button, if isForceModal is true.
I pushed a fix for 'decline all' button to hide.

**Review by dargmuesli — APPROVED** [review]
Great, thank you!

**Pull request merged**
