### PR TITLE
feat(modal): close on click outside

### PR DESCRIPTION
**Pull request by den-kar**
### 📚 Description
This PR adds a feature: click outside the modal content frame to close the modal. It also adds the option `closeModalOnClickOutside` to ModuleOptions.
`closeModalOnClickOutside` default to `false`. To activate this feature, set the new option to `true` in `nuxt.config.ts`
```ts
  ...
  cookieControl: {
    closeModalOnClickOutside: true,
   ...
  },
  ...
```
Resolves #85 

### 📝 Checklist

- [x] All commits follow the Conventional Commit format
- [x] The PR's title follows the Conventional Commit format

### CODE REVIEW

**Comment by den-kar** [comment]
Thank you for the instructions, this is literally my first PR. I've seen, that my first commit missed a `@click.self` modifier on the event listener, that's why I made another commit.
The title looks good to me now. Could you guide me through "Semantic PR — add a semantic commit AND PR title "?

**Review by dargmuesli — COMMENTED** [review]
Well done :+1: be encouraged to tell if something is new to you! I would not have noticed that it was your first PR, you did it very well :)
I quickly extracted the inline method. Would you please extend the README so that the new option is documented there? Then others know about it right away :pray:

**Comment by dargmuesli** [comment]
Now I just changed the order of some methods, which theoretically is a no-no, because it's not on the topic of your pull request, but I was just at it and wanted to prevent merge conflicts. Don't learn from that :wink:

**Comment by den-kar** [comment]
Then I'll learn that communication is key, since everything seems to have worked out :blush:. I've extended the README now.
Thank you for nudging me in the right direction :fist_raised:

**Pull request merged**
