### PR TITLE
feat: add initial recommended state management

### PR DESCRIPTION
**Pull request by KerneggerTim**
### 📚 Description

I implemented a small feature which let’s the website owner choose some recommended cookies. These are only preselected on the first modal open when “isConsentGiven” is undefined. To comply with GDPR no actual cookies are being set - only the checkboxes are preselected so when users click on “accept selected” the recommended cookies will get enabled. 

### 📝 Checklist

- [x] All commits follow the Conventional Commit format
- [x] The PR's title follows the Conventional Commit format

### CODE REVIEW

**Comment by dargmuesli** [comment]
Thank you for the suggestion! Are you sure that preselecting options is in accordance with the GDPR? From all I know it wouldn't be, but I'm at most experienced, not an expert.

**Comment by chrstx** [comment]
Hi, @dargmuesli  is right. I checked with different authorities and preselecting checkboxes is not GDPR-compliant. But as this plugin advertises "highly configurable cookie banner" I think it would be good to implement this feature and to leave the choice to the website provider on how they want to present the cookie banner. As it is in the providers realm of responsibilities I think this feature would be a nice to have if it is turned off by default.
I also get often asked by customers to implement it that way. I inform them about the non-conformity to GDPR but the decision is theirs.

**Review by dargmuesli — COMMENTED** [review]
Alright, please add some documentation for this feature and make sure to note that this is (as it seems) not GDPR compliant. Then, I think, we can merge this.

**Comment by dargmuesli** [comment]
@KerneggerTim are you interested in providing the documentation?

**Comment by KerneggerTim** [comment]
@dargmuesli i added the documentation. please check it.

**Review by dargmuesli — APPROVED** [review]
I've renamed the property to `isPreselected`, which should make the behavior more clear. Thank you for the PR! :green_heart:

**Pull request merged**
