### PR TITLE
feat!: allow to configure cookie options

### PR DESCRIPTION
**Pull request by semiaddict**
BREAKING CHANGE: remove stale `domain` configuration option
feat: add `cookieOptions` configuration option

### 📚 Description

This PR addresses the issue described in #105.

It cleans up the cookie creation code to fully use nuxt's [useCookie](https://nuxt.com/docs/api/composables/use-cookie) where applicable, and allows passing options to useCookie.
Cookie options defaults to setting the path to "/" to be consistent with versions up to `5.9.2`.

### 📝 Checklist

- [x] All commits follow the Conventional Commit format
- [x] The PR's title follows the Conventional Commit format

### CODE REVIEW

**Review by dargmuesli — CHANGES_REQUESTED** [review]
Could you amend the commit message to:
```
feat!: allow to configure cookie options
BREAKING CHANGE: remove `domain` configuration option, add `cookieOptions` configuration option
```
Or something similar. That will allow for an automatic semantic release :)

**Comment by dargmuesli** [comment]
Thank you very much for the PR! :heart:

**Comment by semiaddict** [comment]
> Could you amend the commit message to:
> 
> ```
> feat!: allow to configure cookie options
> BREAKING CHANGE: remove `domain` configuration option, add `cookieOptions` configuration option
> ```
> 
> Or something similar. That will allow for an automatic semantic release :)

Sure, however, this PR doesn't exactly 'remove' the `domain` option, it just cleans it up as it wasn't being used anywhere in the code (even before my changes).

Would something like this work for you then?
```
feat!: allow to configure cookie options
BREAKING CHANGE: remove stale `domain` configuration option, add `cookieOptions` configuration option
```

BTW, what does the exclamation mark before the colon in `feat!:` do?

**Comment by dargmuesli** [comment]
Yes, that would be fine! I just think about people maybe still having a `domain` set, even if it does not do anything, having build errors when that option becomes unavailable.

The exclamation mark does the same as writing "BREAKING CHANGE" to the footer

> BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with [MAJOR](http://semver.org/#summary) in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.

https://www.conventionalcommits.org/en/v1.0.0/

I just like to use both, to make it clear on any level.

**Comment by semiaddict** [comment]
@dargmuesli,
Thanks for the feedback. I learned something new :)

I had to slightly modify the commit message as it didn't pass the linter.
I hope that's alright.

**Comment by dargmuesli** [comment]
Sure, that's perfectly fine!

**Review by dargmuesli — APPROVED** [review]

**Comment by dargmuesli** [comment]
I'm merging this into the `beta` branch first to make a release containing all breaking changes.

**Comment by dargmuesli** [comment]
Thank you very much @semiaddict! :heart:

**Pull request merged**
