### PR TITLE
feat(i18n): add Romanian translation

### PR DESCRIPTION
**Pull request by raducretu**
### 📝 Checklist

- [ ] All commits follow the Conventional Commit format
- [ ] The PR's title follows the Conventional Commit format

### CODE REVIEW

**Comment by raducretu** [comment]
added it according to comment

**Review by dargmuesli — CHANGES_REQUESTED** [review]
Thank you. Please do not forget about the README. To make the pipeline turn green, please also use semantic commit formatting for all commits as I've given an example for by changing the PR's title. You could squash your commits and change the commit title while doing so.

**Comment by dargmuesli** [comment]
@raducretu are you still interested in having this PR merged? Can I assist in any way?

**Pull request merged**
