### PR TITLE
feat(locale): add ID - Bahasa(Indonesian) translation

### PR DESCRIPTION
**Pull request by abdullahhafizh**
### 📚 Description
This PR add new language to the list -> Indonesian (ID)

### 📝 Checklist
- [x] All commits follow the Conventional Commit format
- [x] The PR's title follows the Conventional Commit format

### CODE REVIEW

**Review by dargmuesli — APPROVED** [review]
Thank you! :heart:

**Comment by dargmuesli** [comment]
Just some minor changes needed to keep the linter happy.

**Comment by dargmuesli** [comment]
A `type` specifier seems to be missing still

**Comment by abdullahhafizh** [comment]
Done

**Pull request merged**
