### PR TITLE
Added Azerbaijani locale

### PR DESCRIPTION
**Pull request by chz**
Added Azerbaijani locale

### CODE REVIEW

**Comment by dargmuesli** [comment]
Hello @chz, thank you for your contribution! Please make sure your commits follow the https://www.conventionalcommits.org/ guideline :)

**Review by dargmuesli — CHANGES_REQUESTED** [review]
Also, v4 has just been released. In that version a few locale keys were renamed and `accept` has been added: https://github.com/dargmuesli/nuxt-cookie-control/releases/tag/4.0.0
To preserve commit ownership, please incorporate those changes :)

**Comment by dargmuesli** [comment]
Thank you for the changes, @chz! I'm going to merge those now. Besides, let me point out that the English bannerDescription's text content has slightly changed recently. Reason being that depending on the jurisdiction it might not be enough to say that continuing to use a page equals consent. Feel free to create a separate PR to incorporate that change into the Azerbaijani locale if you want. Thanks again!

**Comment by chz** [comment]
> Thank you for the changes, @chz! I'm going to merge those now. Besides, let me point out that the English bannerDescription's text content has slightly changed recently. Reason being that depending on the jurisdiction it might not be enough to say that continuing to use a page equals consent. Feel free to create a separate PR to incorporate that change into the Azerbaijani locale if you want. Thanks again!

Thanks. Already done. Check PR [https://github.com/dargmuesli/nuxt-cookie-control/pull/35](url)

**Pull request merged**
