### PR TITLE
feat(locale): add zh-CN Mainland China translation

### PR DESCRIPTION
**Pull request by yang1206**
### 📝 Checklist

- [x] All commits follow the Conventional Commit format
- [x] The PR's title follows the Conventional Commit format

### CODE REVIEW

**Review by dargmuesli — COMMENTED** [review]
Thank you for the proposal!
Are the changes to empty lines in the README intended?
And let's use `zh-CN` instead of `zhCN`, ok?

**Comment by yang1206** [comment]
Thank you for pointing out those issues. I'll make the necessary adjustments: restoring the empty lines in the README and using "zh-CN" instead of "zhCN". Appreciate your feedback!

**Review by dargmuesli — APPROVED** [review]
Thank you for the great work!

**Pull request merged**
