### PR TITLE
Update types.ts to allow more cookies group

### PR DESCRIPTION
**Pull request by agracia-foticos**
Update types to allow more cookies group

### 📚 Description

Fix https://github.com/dargmuesli/nuxt-cookie-control/issues/216

### 📝 Checklist

  - feat(component): add new types

### CODE REVIEW

**Review by dargmuesli — CHANGES_REQUESTED** [review]
As mentioned, I'd like these categories to be customizable by the user, keeping the default to the current behavior. So hardcoding arbitrary values won't be an option here, I'm afraid.

**Comment by agracia-foticos** [comment]
i generate new commits with full user customization cookies group, avoid types

**Review by dargmuesli — CHANGES_REQUESTED** [review]
I think those changes do not keep the current behavior as default. Also the project stops working with the current changeset:
image
Maybe try running the playground, the linter and the build to make sure the changes you propose are not breaking.

**Comment by agracia-foticos** [comment]
> I think those changes do not keep the current behavior as default. Also the project stops working with the current changeset: image Maybe try running the playground, the linter and the build to make sure the changes you propose are not breaking.

I feel the inconvenience, here you are a new version. i wait for your notices

**Comment by dargmuesli** [comment]
This changeset still breaks functionality, e.g. when trying to open the modal:

image

Also, it doesn't seem to have gotten the backwards compatibility added back in and the linter shows some errors:

image

I'll close this PR now, as I don't see enough progress towards non-breaking changes. Please only continue contributions that satisfy change requests or the build tooling.

**Pull request closed without merging**
